# Link for useful orbs https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#start
version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start